insert into person (name, email, job, gender, active, city, salary, birthday) values ('Sadye Thurley', 'sthurley0@about.com', 'doctor', 'Female', true, 'Bejing', 4546, '2016-06-07');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Hashim Ramsbotham', 'hramsbotham1@ameblo.jp', 'painter', 'Female', false, 'Helsinki', 14157, '1996-09-26');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Cammy Akess', 'cakess2@sphinn.com', 'singer', 'Female', true, 'Mexico city', 5374, '1986-11-04');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Noah O''Connel', 'noconnel3@hud.gov', 'solider', 'Female', true, 'Saigon', 1209, '1934-10-28');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Hubey Deme', 'hdeme4@live.com', 'developer', 'Female', false, 'Nairobi', 14297, '2020-10-17');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Chan Solano', 'csolano5@dailymail.co.uk', 'cleaner', 'Male', false, 'New York', 4601, '2003-01-19');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Fiorenze Livezley', 'flivezley6@spiegel.de', 'driver', 'Male', false, 'Bejing', 8642, '1984-02-21');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Bogey Papaccio', 'bpapaccio7@joomla.org', 'developer', 'Female', false, 'Cairo', 447, '1957-08-19');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Devondra Gosdin', 'dgosdin8@msu.edu', 'teacher', 'Female', false, 'Jerusalem', 9537, '1966-07-28');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Charlie McCoughan', 'cmccoughan9@tiny.cc', 'chef', 'Male', false, 'Shanghai', 588, '1995-12-07');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Guilbert Jost', 'gjosta@weebly.com', 'doctor', 'Male', true, 'Paris', 5170, '1999-04-09');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Tiertza Felderer', 'tfeldererb@jiathis.com', 'banker', 'Female', false, 'Berlin', 8465, '1992-09-30');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Aurthur Robertelli', 'arobertellic@parallels.com', 'solider', 'Female', true, 'Cairo', 3053, '1970-05-22');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Kelli Bisset', 'kbissetd@admin.ch', 'carpenter', 'Male', true, 'Bangkok', 10361, '1990-02-02');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Sydney Sumbler', 'ssumblere@quantcast.com', 'teacher', 'Female', false, 'Mexico city', 13523, '1976-10-22');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Stace Shattock', 'sshattockf@abc.net.au', 'doctor', 'Male', true, 'Amserdam', 3035, '1998-08-14');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Darcey O''Murtagh', 'domurtaghg@blogs.com', 'chef', 'Male', false, 'Saigon', 4568, '2004-10-15');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Timothee Hugland', 'thuglandh@tripod.com', 'singer', 'Female', true, 'Toronto', 14767, '1981-04-15');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Thorny Braune', 'tbraunei@1und1.de', 'singer', 'Male', false, 'Sanfransico', 14557, '1931-09-30');
insert into person (name, email, job, gender, active, city, salary, birthday) values ('Tildi Mac', 'tmacj@deliciousdays.com', 'painter', 'Male', true, 'Cairo', 7087, '2004-04-25');